title: Hubert Kanyamahanga # your name (or website title) here
logo: "/images/Passport-Photo.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
I am a polyvalent engineer focused on applying technology to solve business problems, and I have dedicated my
career to help others achieve their potential.
I have a background in Data Science and experience in software development with Python, I am truly passionate
about using modern automated systems and machine learning techniques to contribute to the development of
industries. Currently, I am a Software Developer at Wutiko.
  <br><br>
  Second e 
  <br><br>
  <a href="https://www.linkedin.com/in/kanyamahanga-hubert/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
